### ISSUE TITLE
check .htaccess and .htaccess.default or give a hint to manually compare them

### ISSUE THREAD

**Issue by Aybee** [BugBuster1701/contao-easyupdate3#49]
Hi, habe gerade zum ersten Mal easyupdate3 ausprobiert und Contao 3.5.3 auf 3.5.4 geupt. Boh war das easy. Toll gemacht, vielen Dank.

Das ist mir noch aufgefallen: Es müssste ein Hinweis erscheinen, dass man seine **aktuelle .htaccess** mit der **neuen .htaccess.default** abgleicht. Viele Nichtentwickler vergessen dies und betreiben eine Version mit einer alten .htaccess.

**Comment by BugBuster1701** [comment]
Wenn eine neue mitgeliefert wird. Gute Idee, dann auch gleich im Falle für die robots.txt.

**Comment by Aybee** [comment]
Ja, stimmt, danke.

**Comment by Aybee** [comment]
Danke sehr 👍
