### ISSUE TITLE
Startpanel erweitern

### ISSUE THREAD

**Issue by BugBuster1701** [BugBuster1701/contao-easyupdate3#68]
mit der Möglichkeit alte Backups und Update ZIPs zu löschen.
[Forum](https://community.contao.org/de/showthread.php?1607-easyUpdate-Updates-noch-einfacher&p=427921&viewfull=1#post427921)

**Comment by zonky2** [comment]
wenn fertig, geht der nächste "Tomasa-Burger" auf mich... ;-)

**Comment by zonky2** [comment]
btw: muss nicht zwingend in die Systemwartung - könnte auch in Dein "Startpanel" im Backend

**Comment by BugBuster1701** [comment]
So könnte das aussehen:
![grafik](https://cloud.githubusercontent.com/assets/1218809/22170316/87842f8a-df7c-11e6-83e6-d6ce2874ccbf.png)

**Comment by zonky2** [comment]
Bingo!
